
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
    // `prisma migrate` needs a direct (unpooled) session — advisory locks and
    // DDL don't work through Neon's PgBouncer. Locally this equals DATABASE_URL.
    directUrl: env("DIRECT_URL"),
  },
});
