
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // This datasource is only used by the Prisma CLI (migrate / studio / db).
    // It must be the direct, unpooled connection: advisory locks and DDL don't
    // work through Neon's PgBouncer. Locally DIRECT_URL equals DATABASE_URL.
    // The app at runtime connects via @prisma/adapter-pg + process.env
    // .DATABASE_URL (see src/lib/prisma.ts), independent of this block.
    url: env("DIRECT_URL"),
  },
});
